### ISSUE TITLE
Need quick fix for HiveConnector

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/velox#460]
### Description

https://github.com/oap-project/velox/blob/8a6ef2ba9cb4aba82584f093c04daea5b8df57a0/velox/connectors/hive/HiveConnector.cpp#L63C34-L63C34

pass config instead of nullptr. cc @zhouyuan @rui-mo @PHILO-HE

**Comment by philo-he** [comment]
Hi @Yohahaha, I note upstream velox also needs to be modified for this issue. Will you file a PR to upstream? As we are doing daily rebase, upstream's merged PR will be quickly synced to this repo.

**Comment by Yohahaha** [comment]
> Hi @Yohahaha, I note upstream velox also needs to be modified for this issue. Will you file a PR to upstream? As we are doing daily rebase, upstream's merged PR will be quickly synced to this repo.

I already submit to upstream velox, https://github.com/facebookincubator/velox/pull/8014, but not sure when that pr will be merged. 
It would be great if oap-velox could fix this issue first, which affect all adapters including S3, GCS, ABFS and out internal adapter.

**Comment by zhouyuan** [comment]
@Yohahaha can you please also make a patch to oap/velox? looks like a small patch

thanks, -yuan

**Comment by Yohahaha** [comment]
> @Yohahaha can you please also make a patch to oap/velox? looks like a small patch
> 
> thanks, -yuan

Sure, https://github.com/oap-project/velox/pull/463
