### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zhli1142015** [oap-project/velox#483]
### Bug description

https://github.com/oap-project/velox/blame/2024_03_18/velox/dwio/parquet/tests/reader/ParquetTableScanTest.cpp#L508C9-L510C72
__w/1/s/velox/dwio/parquet/tests/reader/ParquetTableScanTest.cpp:511:69: error: expected ')' before ';' token
  511 |   assertSelectWithFilter({"name"}, {}, "", "SELECT (null, 'Jones')");
      |                                                                     ^
      |                                                                     )
/__w/1/s/velox/dwio/parquet/tests/reader/ParquetTableScanTest.cpp:508:11: note: to match this '('
  508 |   loadData(
      |           ^

### System information

Velox System Info v0.0.2
Commit: 73ee6321534f9988716fdba7193de8d2d3091d03
CMake Version: 3.22.1
System: Linux-5.15.146.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by zhli1142015** [comment]
cc @rui-mo  and @zhouyuan , thanks

**Comment by yma11** [comment]
@zhli1142015 I met this issue.  rm `_build` folder and build again can help. Velox has a [commit ](https://github.com/facebookincubator/velox/pull/8988) which may already fix this issue.

**Comment by zhli1142015** [comment]
I thought this maybe a different issue.
`error: expected ')' before ';' token`
![image](https://github.com/oap-project/velox/assets/10524738/39f53878-5dc8-4444-8731-356bdcad908f)

**Comment by yma11** [comment]
<img width="677" alt="image" src="https://github.com/oap-project/velox/assets/11849056/4695110f-74de-4b3a-9c7c-acb890f408f1">

This is the same error I met and rebuild after deleting _build works. But I did not try with latest velox. So above error happens in latest velox?

**Comment by zhli1142015** [comment]
This is found on 3_17 branch, I think 3_18 shoud have same issue. It's reported by our build pipeline which should starts build from a clean environment.
I think `makeRowVector` is missed in line 508 `loadData`.
![image](https://github.com/oap-project/velox/assets/10524738/3103f33e-a9e8-402c-97e6-b52968e9e941)

**Comment by yma11** [comment]
`3_18` rebase has already passed Gluten CI and merged. Let me double check by a local build.

**Comment by zhli1142015** [comment]
I thought velox ut is not covered by Gluten CI.

**Comment by yma11** [comment]
> I thought velox ut is not covered by Gluten CI.

Yes. We don't enable parquet by default in Velox. I can reproduce it and will do a force update on corresponding branches. Thanks for reporting this!

<img width="481" alt="image" src="https://github.com/oap-project/velox/assets/11849056/1089cd7e-1b77-4b83-983a-94b8f1bdcff6">

**Comment by yma11** [comment]
Done. Updated `2024_03_18` and `update` branch.

**Comment by zhli1142015** [comment]
Thanks.
